feat: update link system and UI
reearth/reearth-web pull request #12
Opened 2021-06-07 08:25 UTC by KaWaite

- update link system
- update UI
- fix bugs

2021-06-08 02:49 UTC, rot1024 approved these changes

2021-06-08 04:51 UTC, rot1024 requested changes
There are some ESLint warnings at src/components/atoms/AdditionButton/index.tsx

2021-07-07 06:01 UTC, rot1024 approved these changes

2021-07-08 07:18 UTC, HideBa approved these changes
LGTM 👍 
Is your formatter works wrong?
If so plz format files before you merge not to make unexpected changes.

2021-07-08 07:48 UTC, merged