Fix/workspace settings dont refresh
reearth/reearth-web pull request #167
Opened 2022-01-30 03:10 UTC by issmail-basel

# Overview
[Fixes](https://github.com/reearth/reearth/issues/154) 

## What I've done
Updating team state after crud operation.

## How I tested
- Add new member to workspace
- Edit a member role
- delete a member

## Screenshot

https://user-images.githubusercontent.com/78056580/151685201-9c7c21a2-8b73-4658-a770-9f2f67792b15.mp4

2022-01-31 07:33 UTC, HideBa requested changes
Kindly check my reviews. 👍

2022-02-04 05:27 UTC, HideBa approved these changes
LGTM 👍

2022-02-04 06:21 UTC, rot1024 approved these changes

2022-02-08 02:31 UTC, merged

2022-02-08 09:10 UTC, lavalse commented
@Basel-Issmail When you have time, Can we test this task a little bit again ? Because I test on test env, some similar bug still there