feat: Add opacity field to map tiles
reearth/reearth-web pull request #220
Opened 2022-05-09 06:49 UTC by KaWaite

# Overview

## What I've done

## What I haven't done

## How I tested

## Screenshot

## Which point I want you to review particularly

## Memo

2022-05-09 08:28 UTC, rot1024 requested changes

2022-05-09 08:28 UTC, rot1024 commented on src/components/molecules/EarthEditor/PropertyPane/PropertyField/SliderField/index.tsx
> +const inputRegex = new RegExp(/^\d+\.\d{2,}$/);
```suggestion
const inputRegex = /^\d+\.\d{2,}$/;
```

2022-05-09 08:28 UTC, rot1024 commented on src/components/molecules/EarthEditor/PropertyPane/PropertyField/SliderField/index.tsx
> +  };
```suggestion
  const opacityMarkers = useMemo(() => ({
    [min ?? 0]: min ?? 0,
    [max ? max / 2 : 0.5]: max ? max / 2 : 0.5,
    [max ?? 1]: max ?? 1,
  }), [min, max]);
```

useMemo is just helpful here

2022-05-09 08:28 UTC, rot1024 commented on src/components/molecules/EarthEditor/PropertyPane/PropertyField/SliderField/index.tsx
> +    const target = e?.currentTarget;
```suggestion
  const handleInputChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const target = e.currentTarget;
```

2022-05-09 08:28 UTC, rot1024 commented on src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
> +      [string, ImageryProvider, number | undefined, number | undefined, number | undefined][]
It's hard to understand the slice type when you get to this point. You can define a type:

```suggestion
      ImageryLayerData[]
```

```ts
type ImageryLayerData = {
  id: string;
  provider: ImageryProvider;
  min: number | undefined;
  max: number | undefined;
  opacity: number  | undefined;
}
```

2022-05-09 09:11 UTC, issmail-basel commented on src/components/molecules/Visualizer/Engine/Cesium/hooks.ts
> +          t,
@KaWaite  , can you explain this to me?

2022-05-09 09:11 UTC, issmail-basel approved these changes

2022-05-10 03:21 UTC, rot1024 approved these changes

2022-05-10 03:40 UTC, merged