feat: extend plugin API of camera
reearth/reearth-web pull request #311
Opened 2022-09-07 04:08 UTC by airslice

# Overview

## What I've done

## What I haven't done

## How I tested

## Screenshot

## Which point I want you to review particularly

## Memo

2022-09-12 08:29 UTC, rot1024 requested changes

2022-09-12 08:29 UTC, rot1024 commented on src/components/molecules/Visualizer/Engine/Cesium/useEngineRef.test.tsx
> +      },
```suggestion
      cesiumElement: {
        isDestroyed: () => false,
        scene: {
          camera: {
            position: new Cartesian3(0, 0, 1),
            direction: Cartesian3.clone(Cartesian3.UNIT_X),
            up: Cartesian3.clone(Cartesian3.UNIT_Z),
            right: Cartesian3.clone(Cartesian3.UNIT_Y),
            move: mockMove,
          },
          globe: new Globe(Ellipsoid.UNIT_SPHERE),
        },
      } as any,
```

2022-09-12 08:29 UTC, rot1024 commented on src/components/molecules/Visualizer/Engine/ref.ts
> +  disableScreenSpaceCameraController: () => void;
```suggestion
  enableScreenSpaceCameraController: (enabled: boolean) => void;
```

Combining them is better to reduce duplicated codes

2022-09-14 04:01 UTC, rot1024 approved these changes

2022-09-14 06:24 UTC, KaWaite approved these changes

2022-09-14 06:53 UTC, merged