add the notice
reearth/reearth-web pull request #35
Opened 2021-07-15 05:39 UTC by lavalse

![image](https://user-images.githubusercontent.com/3818046/125734755-851d1b9b-5262-415d-bc88-ebd2338e921a.png)

2021-07-15 05:56 UTC, KaWaite commented on src/components/molecules/Settings/Account/AccountSection/index.tsx
> +`;
You don't need to use styled components. Just use the Icon component directly and it has a color prop you can pass the color into.

2021-07-15 05:57 UTC, KaWaite commented on src/components/molecules/Settings/Account/AccountSection/index.tsx
> +`;
This can be the Flex component. Just use the `otherProperties` prop to pass marginLeft.

2021-07-15 05:58 UTC, KaWaite commented on src/components/molecules/Settings/Account/AccountSection/index.tsx
> +  width: 500px;
If you can move the width into the wrapping Flex(currently the Notice component) I think that is clearer and less prone to issues in the future.

2021-07-15 06:00 UTC, KaWaite commented on translations/en.yml
> +              (For example: public projects will not use light theme).
```suggestion
              Light theme is still in beta. Some UI may still not be supported
              (ie. public projects will not use light theme).
```
Sorry just small change..

2021-07-15 06:01 UTC, KaWaite reviewed
A couple changes but looking good.

2021-07-15 08:59 UTC, HideBa submitted a review, later dismissed
LGTM 👍 
I've added Japanese text, plz commit suggested changes.

2021-07-15 08:59 UTC, HideBa commented on translations/ja.yml
> +            '3911655130': ''
```suggestion
            '2868137144': 'この操作は取り消すことができません。使用中のアセットがないかお確かめください。'
            '3528672691': 'キャンセル'
            '3645414921': '削除'
            '3911655130': 'ワークスペースからアセットを削除します、よろしいですか？'
```

2021-07-15 08:59 UTC, HideBa commented on translations/ja.yml
> +            '142299937': ''
```suggestion
            '142299937': 'グーグルドライブ'
```

2021-07-15 08:59 UTC, HideBa commented on translations/ja.yml
> +              '1359825936': ''
```suggestion
              '734499794': 'グーグルドライブと接続'
              '1359825936': 'Re:EarthはグーグルスプレッドシートとCSVファイルに対応しています。'
```

2021-07-15 08:59 UTC, HideBa commented on translations/ja.yml
> +          '3723856417': ''
```suggestion
          '3017293479': '狭い'
          '3291465140': '角度'
          '3723856417': '広い'
```

2021-07-15 08:59 UTC, HideBa commented on translations/ja.yml
> +          '3037025019': ''
```suggestion
            '463005216': 'ダブルクリックして入力'
        Infobox:
          '3037025019': 'マウスをここにホバーし、"+"をクリックすることでコンテンツを追加'
```

2021-07-15 09:06 UTC, KaWaite approved these changes

2021-07-16 03:46 UTC, lavalse commented
![image](https://user-images.githubusercontent.com/3818046/125888751-881c1961-eb62-4869-aa8c-c0b8826bc3d0.png)
also fix icon distance problem

2021-07-16 04:44 UTC, HideBa requested changes
If you didn't update your main branch, plz update since @rot1024 reset the main branch.

2021-07-16 04:46 UTC, closed without merging

2021-07-16 06:47 UTC, HideBa commented
@lavalse 
For now, this PR has been closed but the changes will be used after the light theme has been released again.  Thanks!