feat(core): support shapefile in reearth/core
reearth/reearth-web pull request #420
Opened 2023-02-03 06:19 UTC by pyshx

# Overview
This PR adds support for shapefile in reearth/core

## What I've done
I've implemented a support for shapefile zip as url (shapefile(.shp) and database file (.dbf) parser) and converted them into geoJSON and then a feature collection.

## What I haven't done
I haven't implement .shx and any other files corresponding to a shapefile zip.

2023-02-03 18:43 UTC, rot1024 approved these changes

2023-02-03 18:44 UTC, rot1024 requested changes
Build is failed. Can you check?
![image](https://user-images.githubusercontent.com/3888696/216682515-745e5fb0-6ecc-4339-9110-30116ca11934.png)

2023-02-06 06:44 UTC, rot1024 approved these changes

2023-02-06 07:13 UTC, KaWaite approved these changes

2023-02-06 08:53 UTC, keiya01 approved these changes

2023-02-07 13:19 UTC, merged